### ISSUE TITLE
Add docstrings to all feedback components and add to docs

### ISSUE THREAD

**Issue by jeffkayne** [trubrics/trubrics-sdk#36]
The [feedback "collect" components](https://github.com/trubrics/trubrics-sdk/tree/main/trubrics/feedback/collect) are missing docstrings explaining the arguments input to each component.

These should also figure in the docs. An example of this implementation with the `DataContext` can be seen here:
- docstrings: https://github.com/trubrics/trubrics-sdk/blob/main/trubrics/context.py
- docs: https://trubrics.github.io/trubrics-sdk/data_context/

All docstrings in this library follow the [Google Style Docstring](https://gist.github.com/redlotus/3bc387c2591e3e908c9b63b97b11d24e)

**Comment by rishabsinghh** [comment]
Hey @jeffkayne , I would like to start working on this issue. Can u guide me?

**Comment by jeffkayne** [comment]
Hello @rishabsinghh, welcome:)

A good place to start would be to view one component, for example the [dash component](https://github.com/trubrics/trubrics-sdk/blob/main/trubrics/feedback/collect/dash.py), and to understand the goal of the component. Running the code snippet in the README.md will give you a feel for what the code does too.

Then, as stated in the description, you can add a docstring to the function with information about what the function does, with descriptions for each function parameter too.

Thanks !

**Comment by rishabsinghh** [comment]
Thanks Jeff :).

**Comment by rishabsinghh** [comment]
Hey @jeffkayne! Just wanted to ask? In the Collect_feedback_component, what does Metadata exactly mean?

**Comment by jeffkayne** [comment]
Metadata is an argument that is fed into the [Feedback data model](https://github.com/trubrics/trubrics-sdk/blob/main/trubrics/feedback/dataclass.py), allowing users to log any data / metrics directly into the feedback .json.

This can typically be things that the user can see on the app that a data scientist has built; like the model prediction, some feature values, explainability metrics etc.

**Comment by jeffkayne** [comment]
Metadata is an argument that is fed into the [Feedback data model](https://github.com/trubrics/trubrics-sdk/blob/main/trubrics/feedback/dataclass.py), allowing users to log any data / metrics directly into the feedback .json.

This can typically be things that the user can see on the app that a data scientist has built; like the model prediction, some feature values, explainability metrics etc.

**Comment by rishabsinghh** [comment]
Oh, got it! Thanks :)

**Comment by jeffkayne** [comment]
in progress #40
