### ISSUE TITLE
Feature request: Collect structured feedback in single issue

### ISSUE THREAD

**Issue by OlivierBinette** [trubrics/trubrics-sdk#55]
I'd like to use Trubrics to easily collect complex, structured feedback into a single issue (e.g., store responses to multiple questions in a single issue). 

As a developer, I want to be able to collect the responses to multiple questions in a single issue. As a user, I want to be able to save progress in an app and come back to it later.

### Example:

I created a toy Streamlit app that uses Trubrics for logging feedback rather than a custom save to json. [Here's the repo](https://github.com/OlivierBinette/trubrics-tests) and you can run it using "make env run_01" if you have make and conda installed.

The app asks a reviewer to look a predictions and record a thumbs up or thumbs down. On a thumbs down, another form appears to ask for more information. I would expect a user to go through around 5-50 predictions to give feedback on a given model.

Trubrics' feedback components are easy to use and very convenient. However, it'd be nice to be able to group together all the feedback collected in a given session, and submit that as a single issue. I'd want to have a table associating each piece of feedback (thumbs up/down and details) with the model's prediction and maybe other features as well. Furthermore, a reviewer may want to save progress on feedback and come back to it later, before submitting a complete issue.

### What have I considered?

I could use feedback metadata to store responses to multiple questions. However, I'd have to build my own UI and save functionality from scratch.

**Comment by OlivierBinette** [comment]
Screenshot from the app. I'd like to be able to submit feedback for all test data points in a single issue.

![Screenshot from 2023-03-21 14-03-29](https://user-images.githubusercontent.com/784901/226701134-b5e27f88-81d0-458f-bcde-d20b65b820d7.png)

**Comment by jeffkayne** [comment]
Hello @OlivierBinette 

Nice idea!

Currently the way I would recommend to do this is with `.st_feedback(type="custom")`. This feedback type allows you to customise the `title` and `description` fields of the saved feedback file as you wish. Therefore you could compound multiple elements into a single string and feed this into the `description` argument. Streamlit's `st.form()` could help you to wrap your components into a form. But yes, the caveat with this is that you wouldn't be able to use trubrics' other types, you'd have to recreate your user buttons / text fields yourself. 

So from this, I see a couple of features:

1. Your exact use case above is very standard, so I think having an open question field in each feedback type should be a core functionality. This would look something like this:
```py
collector.st_feedback("thumbs", collect_description=True)  # default collect_description=False
```

2. Allowing trubrics' current UI components such as "thumbs" and "faces" inside a custom component. Maybe allowing a user to do something like this:
```py
thumbs = collector.st_thumbs_ui()  # just the UI component of thumbs
if thumbs:
  issue = collector.st_issue_ui()  # just the UI component of issue
  slider = st.slider()  # have the option to add your own streamlit components too
  title, description = f"Thumbs: {thumbs}", f"{slider} - {issue}"
  issue = collector.st_feedback("custom", title=title, description=description)
```

Would these features cover your use case?

**Comment by OlivierBinette** [comment]
Hi @jeffkayne, I think this would partly cover the use case and it seems like a good idea to separate UI components from other functionality, but there are still some issues:

- I have to manually format the data to be saved. If I have multiple questions that I want answers to, then I have to manually organize and save the answers when feedback is submitted. That's a lot of boilerplate code.
- There is no standard for how answers to multiple questions are stored and managed on Trubrics. This could make it hard to export and analyze the data in a systematic way.
- There is no way to save and restore a feedback collection session.

### Idea

In FeedbackCollector, feedback *collection* could be separated from feedback *submission*. That is, a feedback collector object could behave as an aggregator of feedback, so that answers to multiple questions can be collected all at once if needed. It would organize the feedback from multiple components in a systematic way, and allow the submission of the feedback at once on Trubrics. Furthermore, the state of a FeedbackCollector object could be restored when needed in order to edit or continue a feedback collection session.

On Trubrics' platform, the detailed answers to questions could be displayed in a table or kept separate from the main issue title, description, and discussion.

### What could this look like?

Here's some API brainstorm for this functionality:

```python
collector = FeedbackCollector(sessionID="my-session-identifier")

question_1 = collector.multiple_choice(
    label="Are you satisfied with the model's aggregate performance?",
    options=["Yes", "No", "Other]
)

if question_1 == "No":
    collector.text_input(
        label="Please provide additional information:"
    )

collector.st_feedback() # Form to submit the feedback
```

In some cases, questions will be tied to choices of particular user inputs. In this case, the FeedbackCollector object should record responses corresponding to all selected user inputs.

```python
collector = FeedbackCollector()

test_case = st.number_input("Select a test case to investigate")
make_plot(test_case) # Show something to give feedback about

collector.thumbs(unique_id=test_case) # Collects feedback for every selected test case.

collector.st_feedback()
```

To be able to save and restore feedback sessions, `to_json()` and `from_json()` functions could be sufficient. This way, in an ML app, you can add a menu option to load previous feedback, or to save progress. For a bit more control on the feedback session, the FeedbackCollector object could keep a pointer to streamlit's session_state object:

```python
collector = FeedbackCollector(session_state=st.session_state, serializer="json") # Serialize FeedbackCollector and session_state to JSON when saving.

collector = FeedbackCollector.from_json("saved.json") # Loads session_state object if available
```

**Comment by OlivierBinette** [comment]
**Other thought:** Instead of having survey components inside of the FeedbackCollector object, this could all be managed as a separate Streamlit survey component. E.g.:

```python
survey = StreamlitSurvey(session_id="my-session-id") # Uses st.session_state to save responses.

question_1 = survey.multiple_choice(...)

collector = FeedbackCollector()

collector.st_feedback(survey_data=survey.data())
```

**Comment by jeffkayne** [comment]
Ok so there are lots of good ideas here, thanks for all that!

In order to break this down further into multiple feature requests, let's have a call.

**Comment by OlivierBinette** [comment]
@jeffkayne So more thoughts/ideas:

I think that collecting structured feedback could be done as follows, without affecting current functionality:
1. Add an attribute named `detailed_feedback` (dict) to `Feedback` objects.
2. Add a parameter `detailed_feedback = None` to Streamlit's FeedbackCollector object and initialize it as a reference to a st.session_state dictionary:
    ```python
    if detailed_feedback is None:
        if "_trubrics_detailed_feedback" not in st.session_state:
            st.session_state["_trubrics_detailed_feedback"] = {}
        self.detailed_feedback = st.session_state["_trubrics_detailed_feedback"]
    ```
3. Define feedback collection functions that affect `detailed_feedback`, but that don't submit the feedback immediately to Trubrics. For example:
    ```python
    def st_thumbs(self, unique_key: Optional[str] = None):
        col1, col2 = st.columns([1, 15])
        with col1:
            up = st.button("👍", key=f"{unique_key}_up")
        with col2:
            down = st.button("👎", key=f"{unique_key}_down")
        
        if up:
            self.detailed_feedback[f"thumbs_{unique_key}"] = True
        elif down:
            self.detailed_feedback[f"thumbs_{unique_key}"] = False
        
        return up, down
    ```
4. In `st_feedback`, add `detailed_feedback=self.detailed_feedback` to the feedback object being saved.

In this way, we can set up multiple or nested questions, and have that automatically be saved to Trubrics or to a local file. For even more convenience, I'd add a "label" argument to feedback collection functions so that the title of the question being asked is displayed automatically and saved alongside the response received.

I think that simple default behavior is the most important thing, but having a stateful FeedbackCollector object that can aggregate more structured feedback when needed is key to having flexibility in what kind of feedback we can gather. Furthermore, most social sciences, UX, and data science researchers are familiar with this kind of survey-like or interview-like feedback collection.

**Comment by OlivierBinette** [comment]
@jeffkayne If it makes more sense to keep survey functionality separate from the FeedbackCollector object, I've started experimenting with some code to do that. Here's some code and a running streamlit example:

https://gist.github.com/OlivierBinette/7a2a3995c65c0fecbf024953154071f1

**Comment by jeffkayne** [comment]
Hello @OlivierBinette,

As discussed, the new 1.3.2 release from PRs #56 & #57 has some changes that solve for some of the features in this thread:

- Trubrics UI components "issue", "faces" and "thumbs" are now available to be used as part of custom feedback
- Custom feedback is more flexible as `.st_feedback(type="custom", user_response={})` now saves a user's response to a completely customisable dictionary, as in this [example](https://github.com/trubrics/trubrics-sdk/blob/main/examples/feedback_apps/custom_example.py). This now allows multiple questions with any streamlit or Trubrics UI component to be combined and saved as a dict to a specific issue.
- Feedback types "thumbs" and "faces" now have an optional open question argument, with `collector.st_feedback(feedback_type="thumbs", open_feedback="Please provide a description")`

I have also created an issue above that tackles saving multiple feedback items to a single json. As mentioned, this has quite some complexity and is not something that we are prioritising for the moment. Please let me know if there are any other major feature requests in this thread that we can pull out into separate issues.

Thanks again for all the feedback 🙏

**Comment by OlivierBinette** [comment]
The PRs look great. The user_response argument makes it so that I can easily collect data separately from issue submission if I want (e.g. using streamlit-survey).
