### ISSUE TITLE
Your app is having trouble loading the streamlit_feedback.streamlit_feedback component

### ISSUE THREAD

**Issue by ProjectsOfMLee** [trubrics/trubrics-sdk#82]
<img width="870" alt="Screenshot 2023-09-16 at 1 07 04 AM" src="https://github.com/trubrics/trubrics-sdk/assets/104241750/9ae664fa-0d7d-4628-bae5-00984c1ea138">

I have this issue with the st_feedback function. Read the docs and tried to fix it but didn't succeed.

**Comment by jeffkayne** [comment]
Hey @ProjectsOfMLee !

Could you provide me with a code snippet and the version of trubrics that you are using?

Thanks

**Comment by ProjectsOfMLee** [comment]
> Hey @ProjectsOfMLee !
> 
> Could you provide me with a code snippet and the version of trubrics that you are using?
> 
> Thanks

I'm using 1.6.1 trubrics. Code below:
```python
    # feedback = collector.st_feedback(
    #     component="default",
    #     feedback_type="thumbs",
    #     open_feedback_label="Provide additional feedback to help us improve",
    #     model="gpt-4-32k",
    #     key=st.session_state.feedback_key
    # ) Your app is having trouble loading the streamlit_feedback.streamlit_feedback component.
```

**Comment by jeffkayne** [comment]
It looks like you have the wrong version of streamlit-feedback installed.

`trubrics==1.6.1` is built with `streamlit-feedback==0.1.2` as an extra dependency. Please try to update trubrics and its streamlit dependencies with `pip install -U "trubrics[streamlit]"`.

If this still doesn't work, can you run a `pip freeze | grep streamlit-feedback` to tell me what version of streamlit-feedback you have?

**Comment by ProjectsOfMLee** [comment]
> pip install -U "trubrics[streamlit]"

Hi, my streamlit-feedback version is 0.1.2, trubrics is 1.6.1 after I ran the update installation

**Comment by jeffkayne** [comment]
From this information, I can't tell what the issue is. This message only displays normally when you are in a development build... Please join our [discord](https://discord.gg/FJ9gVHWW) and MP me, we can arrange a quick call to debug the issue from there.
